### PR TITLE
start CICd with check

### PR DESCRIPTION
**Pull request by phanhuutoan**

### CODE REVIEW

**Comment by phanhuutoan** [comment]
Task linked: [CU-1zgteq9 Eslint + prettier + CI/CD](https://app.clickup.com/t/1zgteq9)

**Review by phanhuutoan — COMMENTED** [review]
run ut

**Review by phanhuutoan — COMMENTED** [review]
/ut-validation

**Review by superknife0512 — APPROVED** [review]

**Review by superknife0512 — APPROVED** [review]

**Review by superknife0512 — APPROVED** [review]
ok to test

**Review by superknife0512 — COMMENTED** [review]
ok to test

**Review by superknife0512 — APPROVED** [review]
ok to test

**Review by quangtho908 — APPROVED** [review]
ok to test

**Review by superknife0512 — APPROVED** [review]
ok to test

**Review by superknife0512 — APPROVED** [review]
ok to test

**Review by superknife0512 — APPROVED** [review]
ok to test

**Review by superknife0512 — APPROVED** [review]
ok to test

**Review by superknife0512 — APPROVED** [review]
ok to test

**Review by superknife0512 — APPROVED** [review]
ok to test

**Review by superknife0512 — APPROVED** [review]
ok to test

**Review by superknife0512 — APPROVED** [review]
ok to test

**Review by superknife0512 — APPROVED** [review]
ok to test

**Review by superknife0512 — APPROVED** [review]
ok to test

**Comment by phanhuutoan** [comment]
|Test Coverage| %                           | values                                                              |
|---------------|:---------------------------:|:-------------------------------------------------------------------:|
|Statements     |16.33%|( 601 / 3679 )|
|Branches       |7.94%  |( 29 / 365 )    |
|Functions      |3.23% |( 23 / 712 )  |
|Lines          |16.11%     |( 542 / 3364 )          |

**Review by superknife0512 — APPROVED** [review]
ok to test

**Review by superknife0512 — APPROVED** [review]
ok to test

**Review by superknife0512 — APPROVED** [review]
ok to test

**Review by superknife0512 — APPROVED** [review]
ok to test

**Review by superknife0512 — APPROVED** [review]
ok to test

**Review by superknife0512 — APPROVED** [review]
ok to test

**Review by superknife0512 — APPROVED** [review]
ok to test

**Review by superknife0512 — APPROVED** [review]
ok to test

**Pull request merged**
