### PR TITLE
CU-1z5hahn - [BUG] Issue when teacher update new score for clientUser…

### PR DESCRIPTION
**Pull request by quangtho908**
Issue when teacher update new score for clientUser

### CODE REVIEW

**Comment by phanhuutoan** [comment]
Task linked: [CU-1z5hahn [BUG] Issue when teacher update new score for clientUser.archievement](https://app.clickup.com/t/1z5hahn)

**Review by quangtho908 — COMMENTED** [review]
task link: https://app.clickup.com/t/1z5hahn

**Review by phanhuutoan — CHANGES_REQUESTED** [review]
Please take a look :D

**Review by phanhuutoan — APPROVED** [review]
ok to test

**Pull request merged**
