### PR TITLE
dev-e2e setup

### PR DESCRIPTION
**Pull request by phanhuutoan**
__E2E boilerplate__

### Task ID 
Example: [https://app.clickup.com/t/1xc60y5]

### Task type
- [ ] Bug
- [ ] Feature
- [x] Enhance
- [ ] Document

### Description
Describe about what this task does.

### Demo video/image
Some demo video should be here, can using youtube link if you want

### CODE REVIEW

**Review by phanhuutoan — COMMENTED** [review]
run validation

**Review by phanhuutoan — COMMENTED** [review]
run validation

**Review by phanhuutoan — COMMENTED** [review]
run validation

**Review by phanhuutoan — COMMENTED** [review]
run validation

**Review by quangtho908 — APPROVED** [review]
ok to test

**Comment by phanhuutoan** [comment]
Total Coverage: <b>67.74%</b>

<details><summary>Coverage Report</summary><table><tbody><tr><th>File</th><th>Branches</th><th>Funcs</th><th>Lines</th><th>Uncovered Lines</th></tr><tr><td colspan='5'><b>src/HeartBeat</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/BuildSchool-FETeam/Prisdom-graphQL/blob/undefined/src/HeartBeat/heatBeat.resolver.ts'>heatBeat.resolver.ts</a></td><td>100%</td><td><b>0%</b></td><td><b>0%</b></td><td><a href='https://github.com/BuildSchool-FETeam/Prisdom-graphQL/blob/undefined/src/HeartBeat/heatBeat.resolver.ts#L1'>1</a>, <a href='https://github.com/BuildSchool-FETeam/Prisdom-graphQL/blob/undefined/src/HeartBeat/heatBeat.resolver.ts#L10'>10</a>, <a href='https://github.com/BuildSchool-FETeam/Prisdom-graphQL/blob/undefined/src/HeartBeat/heatBeat.resolver.ts#L13'>13</a>, <a href='https://github.com/BuildSchool-FETeam/Prisdom-graphQL/blob/undefined/src/HeartBeat/heatBeat.resolver.ts#L16'>16</a>, <a href='https://github.com/BuildSchool-FETeam/Prisdom-graphQL/blob/undefined/src/HeartBeat/heatBeat.resolver.ts#L2'>2</a>, <a href='https://github.com/BuildSchool-FETeam/Prisdom-graphQL/blob/undefined/src/HeartBeat/heatBeat.resolver.ts#L20'>20</a>, <a href='https://github.com/BuildSchool-FETeam/Prisdom-graphQL/blob/undefined/src/HeartBeat/heatBeat.resolver.ts#L24'>24</a>, <a href='https://github.com/BuildSchool-FETeam/Prisdom-graphQL/blob/undefined/src/HeartBeat/heatBeat.resolver.ts#L27'>27</a>, <a href='https://github.com/BuildSchool-FETeam/Prisdom-graphQL/blob/undefined/src/HeartBeat/heatBeat.resolver.ts#L28'>28</a>, <a href='https://github.com/BuildSchool-FETeam/Prisdom-graphQL/blob/undefined/src/HeartBeat/heatBeat.resolver.ts#L29'>29</a>, <a href='https://github.com/BuildSchool-FETeam/Prisdom-graphQL/blob/undefined/src/HeartBeat/heatBeat.resolver.ts#L3'>3</a>, <a href='https://github.com/BuildSchool-FETeam/Prisdom-graphQL/blob/undefined/src/HeartBeat/heatBeat.resolver.ts#L30'>30</a>, <a href='https://github.com/BuildSchool-FETeam/Prisdom-graphQL/blob/undefined/src/HeartBeat/heatBeat.resolver.ts#L33'>33</a>, <a href='https://github.com/BuildSchool-FETeam/Prisdom-graphQL/blob/undefined/src/HeartBeat/heatBeat.resolver.ts#L4'>4</a>, <a href='https://github.com/BuildSchool-FETeam/Prisdom-graphQL/blob/undefined/src/HeartBeat/heatBeat.resolver.ts#L7'>7</a>, <a href='https://github.com/BuildSchool-FETeam/Prisdom-graphQL/blob/undefined/src/HeartBeat/heatBeat.resolver.ts#L8'>8</a></td></tr><tr><td colspan='5'><b>src/common/guards</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/BuildSchool-FETeam/Prisdom-graphQL/blob/undefined/src/common/guards/permission.guard.ts'>permission.guard.ts</a></td><td><b>88.24%</b></td><td>100%</td><td>100%</td><td><a href='https://github.com/BuildSchool-FETeam/Prisdom-graphQL/blob/undefined/src/common/guards/permission.guard.ts#L59'>59</a>, <a href='https://github.com/BuildSchool-FETeam/Prisdom-graphQL/blob/undefined/src/common/guards/permission.guard.ts#L87'>87</a></td></tr><tr><td colspan='5'><b>src/healthCheck</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/BuildSchool-FETeam/Prisdom-graphQL/blob/undefined/src/healthCheck/healthCheck.controller.ts'>healthCheck.controller.ts</a></td><td>100%</td><td><b>0%</b></td><td><b>0%</b></td><td><a href='https://github.com/BuildSchool-FETeam/Prisdom-graphQL/blob/undefined/src/healthCheck/healthCheck.controller.ts#L1'>1</a>, <a href='https://github.com/BuildSchool-FETeam/Prisdom-graphQL/blob/undefined/src/healthCheck/healthCheck.controller.ts#L4'>4</a>, <a href='https://github.com/BuildSchool-FETeam/Prisdom-graphQL/blob/undefined/src/healthCheck/healthCheck.controller.ts#L5'>5</a>, <a href='https://github.com/BuildSchool-FETeam/Prisdom-graphQL/blob/undefined/src/healthCheck/healthCheck.controller.ts#L8'>8</a></td></tr></tbody></table></details>

**Review by quangtho908 — APPROVED** [review]
ok to test

**Comment by phanhuutoan** [comment]
Total Coverage: <b>67.74%</b>

<details><summary>Coverage Report</summary><table><tbody><tr><th>File</th><th>Branches</th><th>Funcs</th><th>Lines</th><th>Uncovered Lines</th></tr><tr><td colspan='5'><b>src/HeartBeat</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/BuildSchool-FETeam/Prisdom-graphQL/blob/undefined/src/HeartBeat/heatBeat.resolver.ts'>heatBeat.resolver.ts</a></td><td>100%</td><td><b>0%</b></td><td><b>0%</b></td><td><a href='https://github.com/BuildSchool-FETeam/Prisdom-graphQL/blob/undefined/src/HeartBeat/heatBeat.resolver.ts#L1'>1</a>, <a href='https://github.com/BuildSchool-FETeam/Prisdom-graphQL/blob/undefined/src/HeartBeat/heatBeat.resolver.ts#L10'>10</a>, <a href='https://github.com/BuildSchool-FETeam/Prisdom-graphQL/blob/undefined/src/HeartBeat/heatBeat.resolver.ts#L13'>13</a>, <a href='https://github.com/BuildSchool-FETeam/Prisdom-graphQL/blob/undefined/src/HeartBeat/heatBeat.resolver.ts#L16'>16</a>, <a href='https://github.com/BuildSchool-FETeam/Prisdom-graphQL/blob/undefined/src/HeartBeat/heatBeat.resolver.ts#L2'>2</a>, <a href='https://github.com/BuildSchool-FETeam/Prisdom-graphQL/blob/undefined/src/HeartBeat/heatBeat.resolver.ts#L20'>20</a>, <a href='https://github.com/BuildSchool-FETeam/Prisdom-graphQL/blob/undefined/src/HeartBeat/heatBeat.resolver.ts#L24'>24</a>, <a href='https://github.com/BuildSchool-FETeam/Prisdom-graphQL/blob/undefined/src/HeartBeat/heatBeat.resolver.ts#L27'>27</a>, <a href='https://github.com/BuildSchool-FETeam/Prisdom-graphQL/blob/undefined/src/HeartBeat/heatBeat.resolver.ts#L28'>28</a>, <a href='https://github.com/BuildSchool-FETeam/Prisdom-graphQL/blob/undefined/src/HeartBeat/heatBeat.resolver.ts#L29'>29</a>, <a href='https://github.com/BuildSchool-FETeam/Prisdom-graphQL/blob/undefined/src/HeartBeat/heatBeat.resolver.ts#L3'>3</a>, <a href='https://github.com/BuildSchool-FETeam/Prisdom-graphQL/blob/undefined/src/HeartBeat/heatBeat.resolver.ts#L30'>30</a>, <a href='https://github.com/BuildSchool-FETeam/Prisdom-graphQL/blob/undefined/src/HeartBeat/heatBeat.resolver.ts#L33'>33</a>, <a href='https://github.com/BuildSchool-FETeam/Prisdom-graphQL/blob/undefined/src/HeartBeat/heatBeat.resolver.ts#L4'>4</a>, <a href='https://github.com/BuildSchool-FETeam/Prisdom-graphQL/blob/undefined/src/HeartBeat/heatBeat.resolver.ts#L7'>7</a>, <a href='https://github.com/BuildSchool-FETeam/Prisdom-graphQL/blob/undefined/src/HeartBeat/heatBeat.resolver.ts#L8'>8</a></td></tr><tr><td colspan='5'><b>src/common/guards</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/BuildSchool-FETeam/Prisdom-graphQL/blob/undefined/src/common/guards/permission.guard.ts'>permission.guard.ts</a></td><td><b>88.24%</b></td><td>100%</td><td>100%</td><td><a href='https://github.com/BuildSchool-FETeam/Prisdom-graphQL/blob/undefined/src/common/guards/permission.guard.ts#L59'>59</a>, <a href='https://github.com/BuildSchool-FETeam/Prisdom-graphQL/blob/undefined/src/common/guards/permission.guard.ts#L87'>87</a></td></tr><tr><td colspan='5'><b>src/healthCheck</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/BuildSchool-FETeam/Prisdom-graphQL/blob/undefined/src/healthCheck/healthCheck.controller.ts'>healthCheck.controller.ts</a></td><td>100%</td><td><b>0%</b></td><td><b>0%</b></td><td><a href='https://github.com/BuildSchool-FETeam/Prisdom-graphQL/blob/undefined/src/healthCheck/healthCheck.controller.ts#L1'>1</a>, <a href='https://github.com/BuildSchool-FETeam/Prisdom-graphQL/blob/undefined/src/healthCheck/healthCheck.controller.ts#L4'>4</a>, <a href='https://github.com/BuildSchool-FETeam/Prisdom-graphQL/blob/undefined/src/healthCheck/healthCheck.controller.ts#L5'>5</a>, <a href='https://github.com/BuildSchool-FETeam/Prisdom-graphQL/blob/undefined/src/healthCheck/healthCheck.controller.ts#L8'>8</a></td></tr></tbody></table></details>

**Pull request merged**
