### PR TITLE
Testx

### PR DESCRIPTION
**Pull request by phanhuutoan**
__Task title: some thing short describing this task__

### Task ID 
Example: [https://app.clickup.com/t/1xc60y5]

### Task type
- [ ] Bug
- [ ] Feature
- [x] Enhance
- [ ] Document

### Description
Describe about what this task does.

### Demo video/image
Some demo video should be here, can using youtube link if you want

### CODE REVIEW

**Review by superknife0512 — APPROVED** [review]
ok to test

**Review by superknife0512 — APPROVED** [review]
ok to test

**Review by superknife0512 — APPROVED** [review]
ok to test

**Review by superknife0512 — APPROVED** [review]
ok to test

**Comment by phanhuutoan** [comment]
Total Coverage: <b>100.00%</b>

<details><summary>Coverage Report</summary><table><tbody><tr><th>File</th><th>Branches</th><th>Funcs</th><th>Lines</th><th>Uncovered Lines</th></tr><tr><td colspan='5'><b>src/adminUser/services</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/BuildSchool-FETeam/schoolX-graphQL/blob/undefined/src/adminUser/services/AdminUser.service.ts'>AdminUser.service.ts</a></td><td>100%</td><td>100%</td><td>100%</td><td></td></tr></tbody></table></details>

**Pull request merged**
